### POST request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Tawer Kidanu",
  "email": "tawe@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}
###